export const ON_AUTH_SUCCESS = "ON_AUTH_SUCCESS";
export const UPDATE_SIGN_IN_LOADING_STATUS = "UPDATE_SIGN_IN_LOADING_STATUS";
export const UPDATE_SIGN_UP_LOADING_STATUS = "UPDATE_SIGN_UP_LOADING_STATUS";
export const SET_APP_DATA = "SET_APP_DATA";
export const DO_LOGOUT = "DO_LOGOUT";
